apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-payroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-payroll
  template:
    metadata:
      labels:
        app: hr-payroll
    spec:
      containers:
        - name: hr-payroll
          image: jpiloto78/hr-payroll:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10