apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-system
  template:
    metadata:
      labels:
        app: hr-system
    spec:
      containers:
        - name: hr-system
          image: jpiloto78/hr-system:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
