apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Launching Kafka directly...";
              echo "broker.id=1" > /tmp/server.properties;
              echo "zookeeper.connect=zookeeper:2181" >> /tmp/server.properties;
              echo "log.dirs=/tmp/kafka-logs" >> /tmp/server.properties;
              echo "listeners=PLAINTEXT://0.0.0.0:9092" >> /tmp/server.properties;
              echo "advertised.listeners=PLAINTEXT://kafka:9092" >> /tmp/server.properties;
              echo "offsets.topic.replication.factor=1" >> /tmp/server.properties;
              kafka-server-start /tmp/server.properties
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LOG_DIRS
              value: /tmp/kafka-logs